# generated by datamodel-codegen:
#   filename:  http://127.0.0.1:8000/openapi.json
#   timestamp: 2022-02-01T23:00:18+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class Item(BaseModel):
    name: str = Field(..., title='Name')
    description: Optional[str] = Field(None, title='Description')
    price: float = Field(..., title='Price')
    tax: Optional[float] = Field(None, title='Tax')
    tags: Optional[List[str]] = Field([], title='Tags')


class ValidationError(BaseModel):
    loc: List[str] = Field(..., title='Location')
    msg: str = Field(..., title='Message')
    type: str = Field(..., title='Error Type')


class HTTPValidationError(BaseModel):
    detail: Optional[List[ValidationError]] = Field(None, title='Detail')
